### PR TITLE
Feature: button field type

### PR DESCRIPTION
**Pull request by NSElvis**
Adds button type field

Example
======

```json
{
    "id":"companies[1].remove",
    "title":"Remove",
    "type":"button",
    "size":{
      "width":20,
      "height":1
    }
}
```

Enabled
======

enabled

Disabled
======

disabled

### CODE REVIEW

**Comment by NSElvis** [comment]
disabled

**Comment by NSElvis** [comment]
enabled

**Comment by zenangst** [comment]
:star: #nohomo

**Comment by NSElvis** [comment]
@zenangst Please delete the branch when you're done :) :leaves:

**Pull request merged**
