### PR TITLE
Add support for dollar signs in formulas

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by NSElvis** [comment]
@zenangst OMG :open_mouth:

**Comment by NSElvis** [comment]
Haha, lol, just saw your implementation, I don't know what to think

**Comment by NSElvis** [comment]
@zenangst I made an issue related to this https://github.com/hyperoslo/NSString-HYPFormula/issues/15

**Comment by zenangst** [comment]
@NSElvis It was done this way to conform to how `$` works in the conditionals. Seeing as how they are optional there, it would make sense to change the entire dictionary structure to make it fit. I might be wrong ;)

**Comment by NSElvis** [comment]
@zenangst I think exactly the same, I just was thinking that `HYPFormula` would be the best place for this kind of implementation.

**Comment by zenangst** [comment]
That is actually true ;)

**Pull request merged**
